pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git "https://github.com/tejalkunde/ecommerce-devops-project.git"
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install --upgrade pip'
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest --maxfail=1 --disable-warnings'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ecommerce-flask .'
            }
        }

        stage('Deploy Docker Container') {
            steps {
                sh '''
                docker stop ecommerce-container || true
                docker rm ecommerce-container || true
                docker run -d --name ecommerce-container -p 5000:5000 ecommerce-flask
                '''
            }
        }
    }
}
